apiVersion: apps/v1
kind: Deployment
metadata:
  name: hack-process-videos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hack-process-videos
  template:
    metadata:
      name: hack-process-videos-pod
      labels:
        app: hack-process-videos-pod
    spec:
      containers:
        - name: hack-process-videos-container
          image: rafaelyuji/microservice-fiap-processa-video:latest
          ports:
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: config-map-deployment-hack-process-videos  
          livenessProbe: # Prova de vida que valida se o pod está saudável
            httpGet:
              path: /health
              port: 3333
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe: # Testa se o container está pronto para receber requisições
            httpGet:
              path: /health
              port: 3333
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: 10m
  selector:
    matchLabels:
      app: hack-process-videos-pod
